### ISSUE TITLE
Notification when assign or re-assigne a merge request.

### ISSUE THREAD

**Issue by kekel87** [chamerling/gitlab-teams#102]
Hello,

In my team we have been looking for a way to have desktop notifications when we are assigned a Merge Request. Your tool is interesting to us, and I think it would be a good idea to add this mechanism.

Thank you

**Comment by chamerling** [comment]
Hello @kekel87,

This is a good idea and should be quite easy to implement here :)

**Comment by chamerling** [comment]
I am on it, hope to have some time this weekend

**Comment by chamerling** [comment]
@kekel87 #107 will be merged tomorrow

**Comment by kekel87** [comment]
Awesome, thanks a lot !

**Comment by chamerling** [comment]
Merged 🍻. Thx again @kekel87 for the idea
