### ISSUE TITLE
Merged/closed MRs should be ordered by update date and not create one

### ISSUE THREAD

**Issue by chamerling** [chamerling/gitlab-teams#15]
Currently MRs are ordered by creation date and not by update date. Proposals:

1. Order by update date
2. Or, provide an order option in the list header which defaults to update date, but which can be changed from a dropdown component

**Comment by rainerkent** [comment]
Hello @chamerling, 
I think I can do this. I can submit a PR for this if you want.

**Comment by chamerling** [comment]
@rainerkent yes please
