### ISSUE TITLE
List all GitLab runners

### ISSUE THREAD

**Issue by chamerling** [chamerling/gitlab-teams#41]
Such feature is already available in Gitlab CE, but it's a necessary endpoint for the following tasks on this epic.

DoD: 
* an administrator of Gitlab should have a list of runners while entering the `Runners` section in the left sidebar (item must be added in the left sidebar)
* a common user should have a message telling that he doesn't have enough rights for this section while entering the `Runners` section. Or, the `Runners` item should not be displayed in such case

**Comment by aduprat** [comment]
I'm on it !
