### ISSUE TITLE
Fix team link in the homepage

### ISSUE THREAD

**Issue by chamerling** [chamerling/gitlab-teams#45]
When on the front page, the team links are broken in the teams 'card'

![Capture d’écran 2019-09-27 à 09 29 25](https://user-images.githubusercontent.com/264403/65750765-75462f80-e109-11e9-8038-343730f3830e.png)

**Comment by Sibin-Thomas** [comment]
Hey, Can I fix this?

**Comment by chamerling** [comment]
@Sibin-Thomas sure!
