### ISSUE TITLE
Open user profile on click

### ISSUE THREAD

**Issue by chamerling** [chamerling/gitlab-teams#51]
Add `@click` handler on user avatar in the popover card. Click on the avatar must open the user profile page `#/user/:username`

![Capture d’écran 2019-09-27 à 15 14 22](https://user-images.githubusercontent.com/264403/65772761-2d400080-e13b-11e9-85fb-a0a7413f751d.png)

**Comment by rajkharvar** [comment]
I would like to work on this.

**Comment by chamerling** [comment]
@rajkharvar great!
