### ISSUE TITLE
Merge requests items are not responsive

### ISSUE THREAD

**Issue by chamerling** [chamerling/gitlab-teams#66]
![Capture d’écran 2019-10-06 à 23 28 32](https://user-images.githubusercontent.com/264403/66276214-1dd65b00-e891-11e9-8877-79352c185c19.png)

TODO: Add ellipsis to text so that comment and like buttons does not overlap over.

**Comment by cdterry87** [comment]
This appears to also be the case on the Issues page.  I can try to take a look at this one, as well.

**Comment by chamerling** [comment]
@cdterry87 thanks!
