### ISSUE TITLE
Add the projects list in the dashboard page

### ISSUE THREAD

**Issue by chamerling** [chamerling/gitlab-teams#75]
As we have teams in the dashboard page, a card with the projects avatars will be nice for quick access 

![Capture d’écran 2019-10-09 à 15 39 37](https://user-images.githubusercontent.com/264403/66486511-083c7d80-eaab-11e9-9b7f-3a42e69fda6a.png)

**Comment by Rocksheep** [comment]
Do you mind if I pick this one up?

**Comment by Rocksheep** [comment]
@chamerling This issue can be closed! 😄
