### ISSUE TITLE
Hide the token field with a password input

### ISSUE THREAD

**Issue by chamerling** [chamerling/gitlab-teams#79]
The token field must be a password input as default and a text field if the user wants to. Use https://v15.vuetifyjs.com/en/components/text-fields#password-input to update it:

![Capture d’écran 2019-10-10 à 09 20 11](https://user-images.githubusercontent.com/264403/66547363-5dc26a00-eb3f-11e9-996e-54e798837091.png)

**Comment by tuananhp-1844** [comment]
i will grab this one

**Comment by tuananhp-1844** [comment]
check it for me. #80
