### ISSUE TITLE
Projects card is broken if there are too many projects

### ISSUE THREAD

**Issue by chamerling** [chamerling/gitlab-teams#91]
![Capture d’écran 2019-10-14 à 11 22 38](https://user-images.githubusercontent.com/264403/66741138-1278c600-ee75-11e9-9777-cb1aaaf3c7a5.png)

TODO: Add a scrollbar

**Comment by saifabusaleh** [comment]
Hi @chamerling ,

I want to take the isuse.

however, I have an issue.
I have 2 projects in gitlab.
When I add the access token with gitlab url, while I can see my name I can't see any project in the list.
Can you please link what can be the issue

Thanks

**Comment by chamerling** [comment]
This card only displays favorited projects.
If you do not have enough projects, you should temporary hardcode them in the Vuex store to have more
