### ISSUE TITLE
When no team is created, add a button in the dashboard card to create one

### ISSUE THREAD

**Issue by chamerling** [chamerling/gitlab-teams#92]
Clean the dashboard card to display a centered + button and avoid this:

![Capture d’écran 2019-10-14 à 12 51 26](https://user-images.githubusercontent.com/264403/66746392-faf40a00-ee81-11e9-99bf-7b14cc7bec4e.png)

Clicking on the button opens the dialog like when clicking on the sidebar one

**Comment by MartijnvAdrichem** [comment]
Can I pick this one up?

**Comment by chamerling** [comment]
@MartijnvAdrichem please do
